// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkyk5PKUizzqyUHOtAAm-BGnHGXOSgaaQ',
    appId: '1:1069888959667:web:5bcb0508ca144f2814ecc6',
    messagingSenderId: '1069888959667',
    projectId: 'cinematica-flutter',
    authDomain: 'cinematica-flutter.firebaseapp.com',
    storageBucket: 'cinematica-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHACZz8O9uE68dxv_ChTzM1euWehO4fh4',
    appId: '1:1069888959667:android:1c8ac586034f152514ecc6',
    messagingSenderId: '1069888959667',
    projectId: 'cinematica-flutter',
    storageBucket: 'cinematica-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-6ne-HF73fo3ylxvdchIad9T9dBL9iao',
    appId: '1:1069888959667:ios:f491971382f9f30e14ecc6',
    messagingSenderId: '1069888959667',
    projectId: 'cinematica-flutter',
    storageBucket: 'cinematica-flutter.appspot.com',
    iosBundleId: 'dev.mmuhamadiev.kinopoisk.search.kinopoiskSearch',
  );
}
